### ISSUE TITLE
spring cloud gcp

### ISSUE THREAD

**Issue by vchrisb** [mgoddard-pivotal/gcp-cloudsql-boot#2]
spring cloud gcp now has build in support to parse `VCAP_SERVICES`
https://docs.spring.io/spring-cloud-gcp/docs/1.1.0.BUILD-SNAPSHOT/reference/htmlsingle/#_cloud_foundry

Maybe good to update this repo to use spring cloud gcp or add a note. 
I found this repo before I learned the native support.

Thx.

**Comment by mgoddard-pivotal** [comment]
Thanks for pointing that out.  This was really meant to illustrate a condition that existed, for a specific customer, at a given time.  I added a note to that effect.
